# Generated by Django 2.0.3 on 2018-03-23 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resarticle',
            options={'verbose_name_plural': '文本资源'},
        ),
        migrations.AddField(
            model_name='resarticle',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='res_articles', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='resarticle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resarticle',
            name='content',
            field=models.TextField(verbose_name='文本内容'),
        ),
        migrations.AlterField(
            model_name='resarticle',
            name='title',
            field=models.CharField(max_length=300, verbose_name='文本标题'),
        ),
    ]
