# Generated by Django 2.0.3 on 2018-03-29 11:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resource', '0002_auto_20180324_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resarticle',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='文本内容'),
        ),
    ]
